### ISSUE TITLE
Fetch comments/discussion

### ISSUE THREAD

**Issue by Freso** [brlcad/gciquotient#2]
Any chance the discussion/comments going on on tickets could also be fetched and preserved together with the other things getting pulled?

**Comment by brlcad** [comment]
Yeah, that's on the list to pull because otherwise all the downloads are a mystery.  The data is there and pulled, just has to be written to a file.

**Comment by brlcad** [comment]
done.  it now writes out the entire task activity set as json.  this includes all the comments and status changes.

**Comment by Freso** [comment]
Thanks!
