### ISSUE TITLE
error: Max retries exceeded with url: /codein-prod.appspot.com

### ISSUE THREAD

**Issue by hellik** [brlcad/gciquotient#3]
as mentioned in the ML, the script stops with: _"error: Max retries exceeded with url: /codein-prod.appspot.com...."_

Traceback log attached.

maybe also some encoding issues seems to there.

thanks.

[error.log](https://github.com/brlcad/gciquotient/files/1655230/error.log)

**Comment by brlcad** [comment]
I think the final error is related to all the SSL warnings that preceded the failure: 

> InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this.

It's renegotiating every transfer trying to get an SSL context and since this is done dozens of times unsuccessfully, you run out of retries on that connection.  This would be a problem with your python openssl install, not the script.  Try:

pip install requests[security]

**Comment by brlcad** [comment]
The encoding issues on the first line can be ignored -- it's printing some utf-8 characters, which isn't going to work unless you are running on a capable terminal, but it's just cosmetic.

**Comment by hellik** [comment]
> Try:
>pip install requests[security]

yes that helped to get rid of all the warnings and the script continues now:
thanks

> python gciq.py --apikey myapikey0815
> GCIQuotient: noun | g─ô-s─ô-─½ kw┼ì-sh╔Önt
>  "the magnitude of a specified characteristic or quality"
> ...saving GCI data to [gci_data]
> ...downloading tasks.......done! (176 tasks)
> ...saving GCI tasks to [gci_data\tasks]................................................................................................................................................................................done!
> ...saving GCI instances to [gci_data\instances]
> #00000: GeoForAll: Create a draft for the GeoForAll website's Resources and References page
>         @ gci_data\instances\2018-01-17 17_19_04-GeoForAll_ Create a draft for the GeoForAll website's Resources and References page_-_OSGeo
> #00001: pgRouting: Mascot with magnifier (svg)
>         @ gci_data\instances\2018-01-16 23_45_06-pgRouting_ Mascot with magnifier (svg)_-_OSGeo
> #00002: OSGeo: add yourself to the OSGeo member map
>         @ gci_data\instances\2018-01-15 17_31_33-OSGeo_ add yourself to the OSGeo member map_-_OSGeo
> [...]

later on at about task 50, it stops with following error:

> [...]
> #00050: GRASS GIS: Design the t-shirt for the next code-sprint
>         @ gci_data\instances\0000-00-00 00_00_00-GRASS GIS_ Design the t-shirt for the next code-sprint_-_OSGeo
> Traceback (most recent call last):
>   File "gciq.py", line 287, in <module>
>     main()
>   File "gciq.py", line 284, in main
>     save_instances(FLAGS.datadir, client, cookies)
>   File "gciq.py", line 246, in save_instances
>     write_instance(instdir, ti, cookies)
>   File "gciq.py", line 149, in write_instance
>     activity = get_instance_activity(instance, cookies)
>   File "gciq.py", line 117, in get_instance_activity
>     return info['results']
> KeyError: 'results'
> 

it's maybe another issue?

thanks

**Comment by brlcad** [comment]
Definitely a different issue -- Does it repeatably halt there?

The GCI website has been timing out today a LOT, and there's no try/catching on the connection requests so they'll stop the script if the site hiccups even once.  Going to look at addressing that tomorrow.

**Comment by hellik** [comment]
tested it again:

> #00050: GRASS GIS: Design the t-shirt for the next code-sprint
>         @ gci_data\instances\0000-00-00 00_00_00-GRASS GIS_ Design the t-shirt for the next code-sprint_-_OSGeo
> Traceback (most recent call last):
>   File "gciq.py", line 287, in <module>
>     main()
>   File "gciq.py", line 284, in main
>     save_instances(FLAGS.datadir, client, cookies)
>   File "gciq.py", line 246, in save_instances
>     write_instance(instdir, ti, cookies)
>   File "gciq.py", line 149, in write_instance
>     activity = get_instance_activity(instance, cookies)
>   File "gciq.py", line 117, in get_instance_activity
>     return info['results']
> KeyError: 'results'

it stops at the same instance.

thanks

**Comment by jmckenna** [comment]
@hellik and I are from the same GCI mentoring organization, and I have run this now on my server and I get the same error (stops at instance #00050, "KeyError: 'results'" on line 117 of gciq.py).

Here is the JSON of that problem instance (i.e. from a manual request from line#115), does it look ok?   It seems to have 2 results (I've cleaned some private information from it for sharing here).  Also, its status is "OUT_OF_TIME", I am not sure if that is important for your script:

````
{"count":2,"next":null,"previous":null,"results":[{"is_tombstoned":false,"kind":1,"program_year":2017,"task_instance_id":1111111111111111,"author":null,"text":"","created":"2018-01-17T17:03:26Z","id":222222222222222,"organization_id":33333333333333,"author_is_student":false,"new_task_instance_status":6,"author_id":null,"task_definition_name":"Design the YYYYYYYYY","old_task_instance_status":1,"attachments":[]},{"is_tombstoned":false,"kind":1,"program_year":2017,"task_instance_id":1111111111111111,"author":{"program_year":2017,"display_name":"XXXXXX","id":4444444444444},"text":"","created":"2018-01-14T21:17:16Z","id":5555555555,"organization_id":33333333333333,"author_is_student":true,"new_task_instance_status":1,"author_id":4444444444444,"task_definition_name":"Design the YYYYYYYYY","old_task_instance_status":1,"attachments":[]}]}
````

**Comment by jmckenna** [comment]
Also, not sure if this is meaningful, but the folder created for that problem instance, inside /gci_data/instances/   is named without a timestamp:

````
0000-00-00 00_00_00-Design the YYYYYYYYY_-_OSGeo
````

**Comment by brlcad** [comment]
Okay so that’s all very telling, clearly data-related.  The time stamp is expected (there is no completion date when the run out of time or abandon or are unassigned etc).  What doesn’t make sense is the key error.  There is clearly a ‘results’ key in the json you show... I’ll see if I can push some debugging for you to run.  Will update you in a few hours after that’s pushed, assuming I don’t find the problem.

Thanks for the help debugging!

**Comment by brlcad** [comment]
I added a minor debugging check and a more structured dumping of the raw data in json.  I don't think it'll succeed just yet, but would you test it and upload your json files?

**Comment by hellik** [comment]
just tested the new version, error message:

`#00050: GRASS GIS: Design the t-shirt for the next code-sprint
        @ gci_data\instances\2018-01-17 17_03_26-5867841293123584-GRASS GIS_ Design the t-shirt for the next code-sprint_-_OSGeo
...WARNING: unknown instance activity result, see activity.json
Traceback (most recent call last):
  File "gciq.py", line 323, in <module>
    main()
  File "gciq.py", line 320, in main
    save_instances(FLAGS.datadir, client, cookies)
  File "gciq.py", line 282, in save_instances
    write_instance(instdir, ti, cookies)
  File "gciq.py", line 168, in write_instance
    attachments = get_instance_attachments(activity)
  File "gciq.py", line 135, in get_instance_attachments
    for attachment in result['attachments']:
TypeError: string indices must be integers`

> but would you test it and upload your json files?

which json files I should upload?

**Comment by hellik** [comment]
> #00050: GRASS GIS: Design the t-shirt for the next code-sprint
>         @ gci_data\instances\2018-01-17 17_03_26-5867841293123584-GRASS GIS_ Design the t-shirt for the next code-sprint_-_OSGeo
> ...WARNING: unknown instance activity result, see activity.json

looking into activity.json of #00050

{
    "detail": "Request was throttled. Expected available in 10.0 seconds."
}

**Comment by jmckenna** [comment]
Indeed this script seems to hit an API limit set by Google.   I get the same error as @hellik    So I added the following to gciq.py:

````
import time   (around line 15)
time.sleep(1)     (around line 134)
`````
That gets me to around instance #292 (we have around 650 instances) and this time activity.json states:
````
"detail": "Request was throttled. Expected available in 15133.0 seconds."
````
And now unfortunately if I re-run the script, I get that error on instance #000   (my IP address must now be throttled by the Google API).

**Comment by brlcad** [comment]
Super insightful, thanks!  I’ll talk with Robert and see if we can’t figure out how to get past this and what specifically is the problem. We got through nearly 2k instances without a problem, maybe just lucky..

Was there anything unusual about #50’s activity.json when it completed?  Maybe unusually long?  Lots of uploads?   It’s curious that it consistently halted there due to rate.  Maybe it’s just your version of python / urllib defaults to a different rate.  How fast do the tasks and downloads tick by before / after you added the sleep?

**Comment by hellik** [comment]
> Lots of uploads?

only one upload (svg file), about 115.9 kB

10 comments by student and mentors

but in one comment, there are some smileys inside, this one here: 😀😀😀

> Maybe it’s just your version of python / urllib defaults to a different rate. 

Jeff and me, we're on different continents and using different python environments.

**Comment by hellik** [comment]
now tried with the same time out configuration as Jeff:

> #00500: GRASS GIS: Design the t-shirt for the next code-sprint
>         @ gci_data\instances\2018-01-08 12_36_24-6164753690918912-GRASS GIS_ Design the t-shirt for the next code-sprint_-_OSGeo
> ...WARNING: unknown instance activity result, see activity.json
> Traceback (most recent call last):
>   File "gciq.py", line 325, in <module>
>     main()
>   File "gciq.py", line 322, in main
>     save_instances(FLAGS.datadir, client, cookies)
>   File "gciq.py", line 284, in save_instances
>     write_instance(instdir, ti, cookies)
>   File "gciq.py", line 170, in write_instance
>     attachments = get_instance_attachments(activity)
>   File "gciq.py", line 137, in get_instance_attachments
>     for attachment in result['attachments']:
> TypeError: string indices must be integers

now I'm up to #00500

activity.json says

```
{
    "detail": "Request was throttled. Expected available in 85382.0 seconds."
}
```

**Comment by hellik** [comment]
#00500

17 comments by mentors and students

6 file uploads, biggest about 1.5 MB

**Comment by brlcad** [comment]
Yeah, I think when the appengine suspects you are DoS'ing, it first locks you out a few times in small amounts, then for a day at a time, and possibly longer if it persists... I'd suggest not re-running it until I hear back from Robert, not that you can until tomorrow, but even then unless there's an update, at least not without throttling the sleep back to a full 10 seconds between instances.

**Comment by brlcad** [comment]
I believe I have a workaround but i'll have to finish it up after some rest.  There are a bunch of calls via the tasking client that are no longer needed (which is a request per instance), thus reducing the overall requests.  It also is keeping connections open by default in at least one plce unnecessarily.  Those coupled with some specific rate throttling should help.  I'll update when it's ready to test.  Thx for your patience.

**Comment by brlcad** [comment]
I just pushed an update that has a throttle variable.  You should be able to set that to 1-10 seconds to get through tasks.  It also picks up where it left off, so if you do get throttled by Google, you can increase the INSTANCE_THROTTLE value and it'll pick up where it left off.
