### ISSUE TITLE
"TypeError: string indices must be integers" when getting attachments

### ISSUE THREAD

**Issue by Freso** [brlcad/gciquotient#4]
```python traceback
...WARNING: unknown instance activity result, see activity.json
Traceback (most recent call last):
  File "gciq.py", line 323, in <module>
    main()
  File "gciq.py", line 320, in main
    save_instances(FLAGS.datadir, client, cookies)
  File "gciq.py", line 282, in save_instances
    write_instance(instdir, ti, cookies)
  File "gciq.py", line 168, in write_instance
    attachments = get_instance_attachments(activity)
  File "gciq.py", line 135, in get_instance_attachments
    for attachment in result['attachments']:
TypeError: string indices must be integers
```

**Comment by Freso** [comment]
Seems to be because the connections gets throttled: `{u'detail': u'Request was throttled. Expected available in 25.0 seconds.'}`

**Comment by brlcad** [comment]
Yes, and it's inconsistent as to who / when / how long .. some see no throttling, others after just a few and significant sleeps...

**Comment by Freso** [comment]
Maybe it could catch the throttling and try again after the expected seconds?

**Comment by brlcad** [comment]
Good idea, I’ll try adding that.  The throttle does increase so it’ll probably need to be a little conservative and throttle from the get-go too.

**Comment by brlcad** [comment]
I just pushed an update that has a throttle variable. You should be able to set that to 1-10 seconds to get through tasks. It also picks up where it left off, so if you do get throttled by Google, you can increase the INSTANCE_THROTTLE value and it'll pick up where it left off.

I didn't get to detecting the throttling, but with the deadline tomorrow, wanted to put what we have out there asap.  Let me know if it works for you.
