### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by xenophenes** [brlcad/gciquotient#5]
Hi!

Thanks very much for creating this project - very helpful. Came across this error:

```
Traceback (most recent call last):
  File "gciq.py", line 328, in <module>
    main()
  File "gciq.py", line 325, in main
    save_instances(FLAGS.datadir, client, cookies)
  File "gciq.py", line 258, in save_instances
    instances = client.ListTaskInstances(page=next_page)
  File "/home/sarah/websites/gciquotient/client.py", line 171, in ListTaskInstances
    r.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error
```

Assuming this just means there isn't a second page of instances to download?

**Comment by brlcad** [comment]
> On Dec 20, 2018, at 9:51 PM, Sarah Conway <notifications@github.com> wrote:
> 
> Hi!
> 
> Thanks very much for creating this project - very helpful. Came across this error:
> 
> Traceback (most recent call last):
>   File "gciq.py", line 328, in <module>
>     main()
>   File "gciq.py", line 325, in main
>     save_instances(FLAGS.datadir, client, cookies)
>   File "gciq.py", line 258, in save_instances
>     instances = client.ListTaskInstances(page=next_page)
>   File "/home/sarah/websites/gciquotient/client.py", line 171, in ListTaskInstances
>     r.raise_for_status()
>   File "/usr/lib/python2.7/site-packages/requests/models.py", line 834, in raise_for_status
>     raise HTTPError(http_error_msg, response=self)
> requests.exceptions.HTTPError: 500 Server Error: Internal Server Error
> Assuming this just means there isn't a second page of instances to download?
> 

I wouldn’t.  I’ve not yet seen that error on any of the downloads I’ve performed, but typically a 500 server error is a bug in the code running server-side.  That could be provoked by bad input, but this is a little tricky to diagnose without being able to reproduce the problem myself.

Cheers!
Sean

**Comment by brlcad** [comment]
I think this is handled now with the different throttle/request code.  Please check if you still can, and comment again if it's still an issue.
