### ISSUE TITLE
TabError on gciq.py

### ISSUE THREAD

**Issue by ykarim** [brlcad/gciquotient#6]
Hi, I get the following TabError when running this script on python3.

>  File "gciq.py", line 75
    return sterilize(convert_to_utf8(instance['modified']) + '-' + convert_to_utf8(instance['id']) + '-' + task_name + "_-_" + convert_to_utf8(instance['organization_name']))
                                                                                                                                                                             ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by brlcad** [comment]
Thought that issue was pushed but apparently not.  Quick fix is to run with python2.

**Comment by brlcad** [comment]
Pushed, should be fixed.
