### ISSUE TITLE
Long task names fail 

### ISSUE THREAD

**Issue by robbyoconnor** [brlcad/gciquotient#7]
Long task titles cause the script to barf: 

`IOError: [Errno 36] File name too long: "../gcidata/tasks/6277372660678656-Mifos - Bug Fix_ Adding 'Specific Due Date' charge to the loan account when date is not given, is not throwing any validation.json"
`

**Comment by Freso** [comment]
Can you post the full Python traceback?

**Comment by robbyoconnor** [comment]
Assuming didnt nuke the site yet, sure

**Comment by robbyoconnor** [comment]
```
GCIQuotient: noun | gē-sē-ī kwō-shənt
 "the magnitude of a specified characteristic or quality"
...saving GCI data to [../gcidatatest]
...downloading tasks..........done! (331 tasks)
...saving GCI tasks to [../gcidatatest/tasks]..........................................................................................................................................................................Traceback (most recent call last):
  File "gciq.py", line 328, in <module>
    main()
  File "gciq.py", line 324, in main
    save_tasks(FLAGS.datadir, client, cookies)
  File "gciq.py", line 240, in save_tasks
    write_task(taskdir, t)
  File "gciq.py", line 66, in write_task
    with open(file_path, 'w') as outfile:
IOError: [Errno 36] File name too long: "../gcidatatest/tasks/6277372660678656-Mifos - Bug Fix_ Adding 'Specific Due Date' charge to the loan account when date is not given, is not throwing any validation.json"
```

**Comment by robbyoconnor** [comment]
I posted some feedback on the mailing list thread as well

**Comment by brlcad** [comment]
Fixed!  Now imposes a 140 character limit on names, truncating and appending '...' when that's exceeded so the name doesn't go over 144 chars.  That's the main relevant limit I could find might be in play here as most linux/bsd/win support 255 char filenames (or greater).  If there's still an error, please report back.  Would be nice to detect the limit.
